apiVersion: v1
kind: Pod
metadata:
  name: sample4
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: sample4-svc
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: sample4-1
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx